language: ruby
rvm:
  - 2.4.0
  - 2.3.3
  - 2.2
  - rbx
matrix:
  include:
    - rvm: 2.4.0
      os: osx
      osx_image: xcode8.2
    - rvm: 2.4.0
      os: osx
      osx_image: xcode7.3
    - rvm: system
      os: osx
      osx_image: xcode8.2
    - rvm: system
      os: osx
      osx_image: xcode7.3
    - rvm: ruby-2.3.2-clang
      env: CXX=clang++
    - rvm: 1.9.3
  allow_failures:
    - rvm: 1.9.3
    - rvm: rbx
  fast_finish: true
bundler_args: --jobs=4 --retry=3
before_install:
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo apt-get update; fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo apt-get install git-svn; fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then gem update --system; fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then gem update bundler; fi
  - if [ "$TRAVIS_OS_NAME" == "osx" -a "$TRAVIS_RUBY_VERSION" == "system" ]; then sudo gem install bundler; fi
  - if [ "$TRAVIS_OS_NAME" == "osx" -a "$TRAVIS_RUBY_VERSION" != "system" ]; then gem update --system; fi
  - if [ "$TRAVIS_OS_NAME" == "osx" -a "$TRAVIS_RUBY_VERSION" != "system" ]; then gem update bundler; fi
script:
  - MAKEFLAGS+=-j8 bundle exec rake checkout compile spec binary --trace
deploy:
  provider: releases
  file: $(git ls-files -o pkg | head -1)
  api_key:
    secure: OMCBceg89uRnU+FIPAPbeOK2pISvV4Cz62r9iTRIGXQCOOXX8M40i77/3DmtkMtc9FEuNyAu1+CH886PL2WtZZPK4CmEU3HuqXz1a5VsCI+zcAZL1tevKvblXOVQ3MG+B/SZRC3rEzGwjk4027WtzCCGoGCLUu4TFJP05+/8XN4=
  skip_cleanup: true
  on:
    tags: true
    condition: $TRAVIS_OS_NAME = osx
    all_branches: true
cache:
  bundler: true
notifications:
  recipients:
    - cowboyd@thefrontside.net
    - bordjukov@gmail.com
