---
language: ruby
rvm:
  - "1.8.7"
  - "1.9.2"
  - "2.0.0"
  - "2.1.0"
  - "2.2.0"
  - "2.3.0"
  - "2.4.0"
  - ruby-head
  - jruby-18mode
  - jruby-19mode
  - rbx-18mode
  - rbx-19mode

matrix:
  allow_failures:
    - rvm: "1.9.3"
    - rvm: jruby-18mode
    - rvm: jruby-19mode
    - rvm: rbx-18mode
    - rvm: rbx-19mode

before_install:
  - git submodule update --init --recursive
