language: ruby
before_install:
  - gem install bundler
rvm:
  - 1.9.3
  - 2.0.0
  - jruby-19mode
  - rbx-19mode
gemfile:
  - Gemfile
  - gemfiles/Gemfile-4-0-stable
notifications:
  email: false
  campfire:
    secure: "CGWvthGkBKNnTnk9YSmf9AXKoiRI33fCl5D3jU4nx3cOPu6kv2R9nMjt9EAo\nOuS4Q85qNSf4VNQ2cUPNiNYSWQ+XiTfivKvDUw/QW9r1FejYyeWarMsSBWA+\n0fADjF1M2dkDIVLgYPfwoXEv7l+j654F1KLKB69F0F/netwP9CQ="
