# For PostgreSQL please see 'database.yml.pgsql'.

development:
  adapter: sqlite3
  database: db/development.sqlite3
  pool: 50
  timeout: 15000
  reaping_frequency: 5
  encoding: UTF8

production:
  adapter: sqlite3
  database: db/production.sqlite3
  pool: 50
  timeout: 15000
  reaping_frequency: 5
  encoding: UTF8

test: &test
  adapter: sqlite3
  database: db/test.sqlite3
  pool: 50
  timeout: 15000
  reaping_frequency: 5
  encoding: UTF8

cucumber:
  <<: *test
