language: ruby
rvm:
 - 1.9.3
 - 2.0.0
 - 2.1.0
gemfile:
  - test/gemfiles/Gemfile-rails-4-0
  - test/gemfiles/Gemfile-rails-4-1
  - test/gemfiles/Gemfile-sprockets-2-11
  - test/gemfiles/Gemfile-sprockets-2-8
  - Gemfile
before_install: gem install bundler
script: bundle exec rake test
notifications:
  email: false
  irc:
    on_success: change
    on_failure: always
    channels:
      - "irc.freenode.org#rails-contrib"
  campfire:
    on_success: change
    on_failure: always
    rooms:
      - secure: "CGWvthGkBKNnTnk9YSmf9AXKoiRI33fCl5D3jU4nx3cOPu6kv2R9nMjt9EAo\nOuS4Q85qNSf4VNQ2cUPNiNYSWQ+XiTfivKvDUw/QW9r1FejYyeWarMsSBWA+\n0fADjF1M2dkDIVLgYPfwoXEv7l+j654F1KLKB69F0F/netwP9CQ="
